name: Python application

on:
  push:
    branches: [main]  # Trigger the workflow when pushing to the main branch
  pull_request:
    branches: [main]  # Trigger the workflow on PR creation or update

jobs:
  build:
    runs-on: ubuntu-latest  # The environment to run the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python
      with:
        python-version: '3.x'  # Use Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies if you have a requirements file

    - name: Run the digital clock script
      run: |
        python digital_clock.py  # Replace with your script filename

